### ISSUE TITLE
add collaborator

### ISSUE THREAD

**Issue by ingbrzy** [ashtefan/Romanian_MIUI8#2]
Please add @MarkH-UK as collaborator... thanks..

**Comment by redmaner** [comment]
Add MarkH-UK and revert dee41c08cdc0e91f4aaa8ffd8a3f5e9355120c8f
The untranslateables will be fixed for you  autmatically by translators.xiaomi.eu when MarkH-UK is added as a collaborator.

Thanks in advance

**Comment by ingbrzy** [comment]
still no access... can you check it?

**Comment by ashtefan** [comment]
Checked. Invitation was sent.

**Comment by ashtefan** [comment]
![github_invite](https://cloud.githubusercontent.com/assets/11144312/19516722/063c0b7e-9606-11e6-86b5-747c6f0244ab.jpg)
It's OK to comment all those lines in order not to translate them again later?
<string name="defaultnumber">000000</string> to be replaced with
 ?

**Comment by ingbrzy** [comment]
no... leave them there... after Mark accept invitation, they will be removed automatically..
