### ISSUE TITLE
Xioami note pro fara semnal

### ISSUE THREAD

**Issue by cretzu03** [ashtefan/Romanian_MIUI8#3]
Salut,

Am si eu o problema si nu reusesc sa ii dau de cap.

De 2 saptamani am ramas fara semnal la telefon. Nu mai recunoaste nici o cartela pe nici un slot.
L-am lasat intr-un service in Craiova si nu au reusit sa il fac. Doar mi-au zis ca este o problema de soft.
Acum am observat ca din 64 gb imi recunoaste doar 9gb.

Ma poti ajuta?

draghicirobertadrian@yahoo.com 0746021121

Multumesc!

**Comment by ashtefan** [comment]
http://forum.softpedia.com/topic/1044540-xiaomi-redmi-note-3-pro/page__st__8406 
Scrie aici problema ta si te ajuta baietii:
