### ISSUE TITLE
Buguri

### ISSUE THREAD

**Issue by kkarote** [ashtefan/Romanian_MIUI8#4]
Salut am o luna de cand am telefonul xiaomi redmi note 4 si vreau sa prezint anumite probleme ,care nu cred ca pot fi rezolvate:
1. nu pot conecta telefonul la aplicatia mi Suite cu debug mode sau fara
2. unele aplicatii de regula jocuri nu merg de pilda ,pokemon go am vrut sa vad cum e si alte jocuri aleatorii a caror nume nu le mai tin minte in rest programele sa zic de baza merg perfect facebook , skype, word, excel, adobe, maps, magazinu play(bineinteles), waze...
3. am vazut pe youtube anumite functii pe care le poate folosi miui 8 si unele nu mergeau de pilda long screen shot nu merge am testat pe diferite situri lungeste da doar un pic cam 1-2 cm atat am vazut ca se pot ascude aplicatii, nu gasesc aceasta functie adica nu apare nu cred co voi folosi
4. ori de cate ori schimb datele mobile de pe o cartela pe alta opreste operatorii si reia iar uneori in loc sa aibe viteza 4g are 3g se mai intampla si imi apare si un mesaj de avertizare sa dau restart
5. camera bunicica mai buna decat la telefonu vechi are o problema aplicatia are momente mai rare da sunt cand nu se conecteaza la camera restartez telefonu merge atunci am facut un mic test de stres zis la camera filmand cu modul incetinitor si are momente cand se blocheaza imi iese din aplicatie imi zice ca aplicatia nu raspunde si iese peorma reintru si merge normal.

In rest merge bine mersi foarte multumit traducere buna mai sunt mici scapari da care nu ma prea intereseaza . as dori daca se poate sa imi dati o solutie ca sa pot incerca pokemon go imi apare mesajul your os is not compatible.

O zi buna.

**Comment by ashtefan** [comment]
Salut, eu nu am modelul asta de telefon,  deci nu te pot ajuta. 
Scrie problemele astea in topicul dedicat modelului tau si vei primi ajutor, cu siguranta.
