### ISSUE TITLE
Lipsa traducere

### ISSUE THREAD

**Issue by rdanielf** [ashtefan/Romanian_MIUI8#5]
In Secțiunea wifi apare switch between data and wlan

**Comment by ashtefan** [comment]
Pe ce telefon? Pune si o captura de ecran.

**Comment by rdanielf** [comment]
Redmi note 3 pro

**Comment by rdanielf** [comment]
![screenshot_2016-11-26-15-20-30-850_com android settings](https://cloud.githubusercontent.com/assets/23747078/20640659/a79608e0-b3ec-11e6-8cc1-c878ca199696.png)

**Comment by rdanielf** [comment]
Mai am găsit ceva, atașez.....

**Comment by rdanielf** [comment]
![screenshot_2016-11-26-15-26-56-601_com android settings](https://cloud.githubusercontent.com/assets/23747078/20640672/0573adaa-b3ed-11e6-81a7-3ba47f892bde.png)

**Comment by ashtefan** [comment]
Eu nu am RN3 si deci nu pot verifica toate traducerile pentru toate modelele de telefoane Xiaomi. Oricum traducerea se actualizează în fiecare săptămână, iar randurile de tradus apar tarziu si nu exista timp pentru integrarea lor inaintea compilarii ROM-urilor. Deci va exista mereu un delay in traducere.
