### ISSUE TITLE
problema update

### ISSUE THREAD

**Issue by raduvali** [ashtefan/Romanian_MIUI8#6]
salut
am cumparat un Redmi note 4 de pe aliexpress topone care mi-a venit cu versiune rom MIUI 8.1 by xiaomi.eu 6.9.29/Beta. din cate am citit pe xiaomi.eu pt a face update de rom doar trebuie sa descarc manual rom-ul si sa fac upate... ”So we decided to STOP OTA support at all.. you have to download ROM manually and install via Updater - menu (...) - Select installation package - reboot (You will not loose your data)”     
problema e ca nu merge la mine....ma bag in meniu, selectez pachetul de actualizare se restarteaza telefonul dar fara nici-o instalare noua, ramane acelasi rom!. oare care ar fi problema/? precizez ca nu am instalat niciodata un rom in vre-un telefon, orice update am facut la telefoane a fost doar cel oficial!. te rog sfatuieste-ma ce am de facut!. multumesc

**Comment by ashtefan** [comment]
Pasii de urmat sunt:
-deblocare bootloader(daca este blocat) 
-instalare TWRP pentru modelul tau de telefon
-descarcare si instalare ROM specific telefonului tau(este denumit generic nikel).
